---
name: Local Release

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - '**.md'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '00 03 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  local-release:
    name: Local Release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # We need to do this because of:
      # https://github.com/actions/checkout/issues/290 and its side-effects
      # as https://github.com/goreleaser/goreleaser/issues/2919
      - name: Fetch full annotated tags metadata
        run: git fetch --force --tags

      - name: Set up makesystem
        run: make makesystem_install

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          install-only: true

      - name: Run GoReleaser Local Release Without Signing
        run: make goreleaser_local_release_skip_signing
